config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'pages#home'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/home', to: 'pages#dashboard', as: 'dashboard_home'
  get 'recipe_suggestions/index', as: 'recipe_suggestions'

  # 利用規約とプライバシーポリシー
  get 'terms', to: 'pages#terms', as: 'pages_terms'
  get 'privacy', to: 'pages#privacy', as: 'pages_privacy'
  # ユーザー情報関連のルーティング
  resources :users do
    collection do
      get 'goal'
      get 'gender_age'
      get 'height_weight_target_weight'
      get 'activity_level'
      get 'allergies'
      get 'confirmation', to: 'users#confirmation'
      post 'save_goal', to: 'users#save_goal'
      post 'save_gender_age', to: 'users#save_gender_age'
      post 'save_height_weight_target_weight', to: 'users#save_height_weight_target_weight'
      post 'save_activity_level', to: 'users#save_activity_level'
      post 'save_allergies', to: 'users#save_allergies'
    end
    member do
      delete :destroy
    end
  end

  # プロフィール
  resource :profile, only: %i[show edit update]

  # ダッシュボード
  resources :dashboard, only: [:index]

  # レシピ関連
  resources :recipes, only: [:index, :show] do
    collection do
      get 'search'  # => /recipes/search
      get 'search_results'  # => /recipes/search_results
      get 'recipes/:id', to: 'recipes#show', as: :recipe
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  def self.search(keywords)
    keywords = [keywords].flatten  # # 配列に変換
    query_parts = keywords.map { |keyword| "title LIKE ?" }
    where(query_parts.join(" OR "), *keywords.map { |keyword| "%#{keyword}%" })
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_services
  # カロリー数値が空ではないかチェック
  def index
    if params[:calories].blank?
      flash.now[:alert] = t('.fail')
      render 'recipe_suggestions/index'
      nil
    else
      allergies = []
      if session[:allergy_item_ids].present?
        allergies = AllergyItem.where(id: session[:allergy_item_ids]).pluck(:name)  # AllergyItem モデルからIDに該当するアレルギー項目を検索し、その名前を配列で取得
      end
      free_word = params[:free_word]
      disliked_foods = params[:disliked_foods]
      @recipe = @open_ai_service.generate_recipe(params[:calories], allergies, disliked_foods, free_word)  # メソッド呼び出してレシピテキスト生成
      @translated_recipe = @deepl_service.translate(@recipe, "JA")

      parse_recipes(@translated_recipe)  # 朝食、昼食、夕食の各セクションを抽出
    end
  end

  def show
    recipe_id = params[:id]
    deepl_service = DeepLService.new
    @recipe_details = SpoonacularService.fetch_recipe_information(recipe_id)  # IDのレシピの詳細情報を取得
    if @recipe_details.nil?
      flash.now[:alert] = t('.fail')
    else
      @translated_description = deepl_service.translate(@recipe_details["summary"], "JA")  # 日本語に翻訳
    end
  end

  def search;end

  def search_results
    deepl_service = DeepLService.new
    translated_queries = translate_queries(params[:query], deepl_service)  # ユーザーが入力した検索クエリを英語に翻訳
    @recipes = search_and_transform_recipes(translated_queries, deepl_service)  # 翻訳されたクエリに基づいてレシピを検索し結果を変換
    render :search_results
  end

  def autocomplete
    query = params[:query]
    response = SpoonacularService.autocomplete(query: query, number: 10)
    render json: response
  end

  private

  def parse_recipes(translated_recipe)
    @breakfast, @lunch, @dinner = extract_meals(translated_recipe)
  end

  def extract_meals(translated_recipe)
    breakfast_start = translated_recipe.index("朝")  # 各単語のインデックスで検索
    lunch_start = translated_recipe.index("昼")
    dinner_start = translated_recipe.index("夜") || translated_recipe.index("夕")

    breakfast = extract_meal(translated_recipe, breakfast_start, lunch_start)  # レシピのテキストから朝食、昼食、夕食の各部分を抽出しローカル変数に格納
    lunch = extract_meal(translated_recipe, lunch_start, dinner_start)
    dinner = extract_meal(translated_recipe, dinner_start, translated_recipe.length)

    [breakfast, lunch, dinner]
  end

  def extract_meal(recipe_text, start_index, end_index)  # start_index と end_index の間のテキストを抽出し見つからなければnilを返す
    return nil unless start_index
    recipe_text[start_index...end_index].strip
  end

  def set_services
    @open_ai_service = OpenAiService.new  # APIサービスを利用する準備
    @deepl_service = DeepLService.new
  end

  def translate_queries(query_string, deepl_service)
    query_string.split(/,\s*/).map do |query|  # クエリ文字列を個別の検索語に分割
      deepl_service.translate(query, "EN")  # 各クエリに対して英語に翻訳
    end.reject(&:blank?)
  end

  def search_and_transform_recipes(queries, deepl_service)
    queries.each_with_object([]) do |query, recipes|
      response = SpoonacularService.search(query: query)  # 各翻訳されたクエリに基づいてレシピを検索
      next if response["error"]
      response["results"].each do |recipe|
        translated_title = deepl_service.translate(recipe["title"])
        recipes << {
          id: recipe["id"],
          title: translated_title,
          image: recipe["image"]
        }
      end
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="pt-10 mb-20 bg-teal-100 min-h-screen flex justify-center items-start">
  <div class="card w-full max-w-4xl bg-white shadow-xl mt-10">
    <div class="card-body p-6">
      <div class="flex justify-center">
        <%= image_tag 'recipe.jpg', alt: t('recipes.index.logo_alt'), class: 'w-48 h-32' %>
      </div>
      <h1 class="card-title text-center text-xl"><%= t('recipes.index.title') %></h1>
        <p class="text-center text-gray-500 text-sm"><%= t('recipes.index.subtitle') %></p>
      <div class="border-b border-gray-200 mb-4"></div>
        <% if @breakfast %>
          <h2 class="text-2xl font-bold mb-2">朝食</h2>
          <p class="text-lg mb-4"><%= @breakfast %></p>
        <% end %>

        <% if @lunch %>
          <h2 class="text-2xl font-bold mb-2">昼食</h2>
          <p class="text-lg mb-4"><%= @lunch %></p>
        <% end %>

        <% if @dinner %>
          <h2 class="text-2xl font-bold mb-2">夕食</h2>
          <p class="text-lg"><%= @dinner %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="flex items-start justify-center min-h-screen bg-gray-100 sm:mb-16">
  <div class="w-full max-w-md px-4 pt-8">
    <h1 class="text-2xl font-bold text-center font-zenmaru"><%= t('search.title') %></h1>
    <p class="text-center text-sm text-gray-500 font-zenmaru mb-8">
      <%= t('search.description') %>
    </p>
    <%= form_with url: search_results_recipes_path, method: :get, local: true do |f| %>
      <div class="relative flex items-center justify-center" data-controller="autocomplete">
        <%= f.text_field :query,
            placeholder: t('search.placeholder'),
            class:"block w-full py-2 pl-4 pr-10 text-sm font-zenmaru rounded-md border border-gray-300 focus:border-blue-500 focus:ring-blue-500", 
            data: { autocomplete_target: "input" } %>
        <ul data-autocomplete-target="suggestions" class="suggestions"></ul>
        <button class="absolute right-0 p-2 text-gray-500 rounded-r-md hover:text-white hover:bg-blue-500">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/search_results.html.erb
<div class="bg-white min-h-screen pt-16 px-8">
  <h1 class="text-3xl font-bold text-center"><%= t('search_results.title') %></h1>
  <% if @recipes.empty? %>
    <div class="mt-8 max-w-lg mx-auto">
      <p class="text-center text-gray-600">検索結果がありません。</p>
    </div>
  <% else %>
    <div class="mt-8 mb-24 max-w-lg mx-auto grid grid-cols-1 gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
      <% @recipes.each do |recipe| %>
        <div class="rounded overflow-hidden shadow-md">
          <%= image_tag recipe[:image], class: "w-full aspect-square object-cover" %>
          <div class="px-6 py-4">
            <%= link_to recipe[:title], recipe_path(recipe[:id]), class: "text-blue-500 hover:text-blue-800" %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container mx-auto px-4">
  <h1 class="text-2xl font-bold text-center my-4"><%= @recipe_details["title"] %></h1>
  <%= image_tag @recipe_details["image"], class: "w-full max-w-lg mx-auto rounded-lg shadow-md" if @recipe_details["image"].present? %>
  <p class="text-gray-600 mt-4"><%= @translated_description.html_safe %></p>
</div>