config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'pages#home'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/home', to: 'pages#dashboard', as: 'dashboard_home'
  get 'recipe_suggestions/index', as: 'recipe_suggestions'

  # 利用規約とプライバシーポリシー
  get 'terms', to: 'pages#terms', as: 'pages_terms'
  get 'privacy', to: 'pages#privacy', as: 'pages_privacy'
  # ユーザー情報関連のルーティング
  resources :users do
    collection do
      get 'goal'
      get 'gender_age'
      get 'height_weight_target_weight'
      get 'activity_level'
      get 'allergies'
      get 'confirmation', to: 'users#confirmation'
      post 'save_goal', to: 'users#save_goal'
      post 'save_gender_age', to: 'users#save_gender_age'
      post 'save_height_weight_target_weight', to: 'users#save_height_weight_target_weight'
      post 'save_activity_level', to: 'users#save_activity_level'
      post 'save_allergies', to: 'users#save_allergies'
    end
    member do
      delete :destroy
    end
  end

  # プロフィール
  resource :profile, only: %i[show edit update]

  # ダッシュボード
  resources :dashboard, only: [:index]

  # レシピ関連
  resources :recipes, only: [:index, :show] do
    collection do
      get 'search'  # => /recipes/search
      get 'search_results'  # => /recipes/search_results
      get 'recipes/:id', to: 'recipes#show', as: :recipe
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  include Sorcery::Model
  mount_uploader :avatar, AvatarUploader
  before_validation :set_skip_special_validation
  before_create :set_default_timestamps

  attr_accessor :skip_special_validation

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true
  validates :email, uniqueness: { scope: :deleted_at }, presence: true

  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }, unless: :skip_special_validation?
  validates :height, :weight, presence: true, numericality: { greater_than: 0 }, unless: :skip_special_validation?

  has_many :weight_logs, dependent: :destroy
  has_many :user_allergies, dependent: :destroy
  has_many :allergy_items, through: :user_allergies
  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications

  enum gender: { man: 0, woman: 1 }
  enum goal: { standard: 0, slim_muscle: 1 }
  enum activity_level: { low: 0, moderate: 1, high: 2 }

  private

  def skip_special_validation?
    skip_special_validation == true
  end

  def set_skip_special_validation
    self.skip_special_validation = true if new_record? && password.present? && email.present?
  end

  def set_default_timestamps
    self.created_at ||= Time.current
    self.updated_at ||= Time.current
  end

  def active_for_authentication?
    super && deleted_at.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show;end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.goal = session[:goal]
    @user.gender = session[:gender]
    @user.age = session[:age]
    @user.height = session[:height]
    @user.weight = session[:weight]
    @user.target_weight = session[:target_weight]
    @user.activity_level = session[:activity_level]
    @user.allergy_item_ids = session[:allergy_item_ids]
    @user.tdee = session[:tdee]
    @user.bmr = session[:bmr]
    @user.target_calorie = session[:target_calorie]
    if @user.save
      session[:user_id] = @user.id
      @weight_log = @user.weight_logs.create(weight: @user.weight, date: Time.zone.today)
      redirect_to dashboard_home_path, notice: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render new_user_path, status: :unprocessable_entity
    end
  end

  def goal
  end

  def save_goal
    @goal_form = GoalForm.new(goal: goal_params[:goal])
    if @goal_form.valid?
      session[:goal] = goal_params[:goal]
      redirect_to gender_age_users_path
    else
      flash.now[:alert] = t('.fail')
      render :goal, status: :unprocessable_entity
    end
  end

  def gender_age
  end

  def save_gender_age
    @gender_age_form = GenderAgeForm.new(gender_age_params)
    if @gender_age_form.valid?
      session[:gender] = @gender_age_form.gender
      session[:age] = @gender_age_form.age
      redirect_to height_weight_target_weight_users_path
    else
      flash.now[:alert] = t('.fail')
      render :gender_age, status: :unprocessable_entity
    end
  end

  def height_weight_target_weight
  end

  def save_height_weight_target_weight
    @height_weight_form = HeightWeightTargetWeightForm.new(height_weight_target_weight_params)
    if @height_weight_form.valid?
      session[:height] = @height_weight_form.height
      session[:weight] = @height_weight_form.weight
      session[:target_weight] = @height_weight_form.target_weight
      redirect_to activity_level_users_path
    else
      flash.now[:alert] = t('.fail')
      render :height_weight_target_weight, status: :unprocessable_entity
    end
  end

  def activity_level
  end

  def save_activity_level
    @activity_level_form = ActivityLevelForm.new(activity_level_params)
    if @activity_level_form.valid?
      service = RegistrationService.new(@activity_level_form, session)  # 活動レベルのデータとセッション情報を渡す
      service.process_registration
      redirect_to allergies_users_path
    else
      flash.now[:alert] = t('.fail')
      render :activity_level, status: :unprocessable_entity
    end
  end

  def allergies
  end

  def save_allergies
    @allergies_form = AllergiesForm.new(allergies_params)
    session[:allergy_item_ids] = @allergies_form.allergy_item_ids.reject(&:blank?)
    if @allergies_form.valid?
      redirect_to confirmation_users_path
    else
      flash.now[:alert] = t('.fail')
      render :allergies, status: :unprocessable_entity
    end
  end

  def confirmation
    @user = User.new(session[:user_data])
    @goal = session[:goal]
    @gender_key = session[:gender]
    @age = session[:age]
    @height = session[:height]
    @weight = session[:weight]
    @target_weight = session[:target_weight]
    @activity_level_key = User.activity_levels.key(session[:activity_level])
    if session[:allergy_item_ids].present?
      @allergy_names = AllergyItem.where(id: session[:allergy_item_ids]).pluck(:name).join(",")
    else
      @allergy_names = "なし" # アレルギー情報がない場合の処理
    end
  end

  private

  def set_skip_special_validation
  end

  def goal_params
    params.permit(:goal)
  end

  def gender_age_params
    params.permit(:gender, :age)
  end

  def height_weight_target_weight_params
    params.permit(:height, :weight, :target_weight)
  end

  def activity_level_params
    params.permit(:activity_level)
  end

  def allergies_params
    params.permit(allergy_item_ids: [])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/activity_level.html.erb
<div class="bg-teal-100 min-h-screen">
  <div class="absolute top-16 left-0 right-0 w-full animate-float1">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 640">
      <path fill="#5eead4" fill-opacity="1" d="M0,192L48,197.3C96,203,192,213,288,224C384,235,480,245,576,218.7C672,192,768,128,864,122.7C960,117,1056,171,1152,192C1248,213,1344,203,1392,197.3L1440,192L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
    </svg>
  </div>
  <div class="absolute top-18 left-0 right-0 w-full animate-float2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#5eead4" fill-opacity="0.5" d="M0,256L34.3,245.3C68.6,235,137,213,206,197.3C274.3,181,343,171,411,170.7C480,171,549,181,617,197.3C685.7,213,754,235,823,229.3C891.4,224,960,192,1029,181.3C1097.1,171,1166,181,1234,170.7C1302.9,160,1371,128,1406,112L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path>
    </svg>
  </div>
  <div class="max-w-lg mx-auto p-6 relative z-10">
    <ul class="steps steps-primary font-zenmaru">
      <li class="step step-primary"><%= t('activity_level.steps.goal') %></li>
      <li class="step step-primary"><%= t('activity_level.steps.profile') %></li>
      <li class="step step-primary"><%= t('activity_level.steps.weight') %></li>
      <li class="step step-primary"><%= t('activity_level.steps.activity') %></li>
      <li class="step"><%= t('activity_level.steps.allergies') %></li>
      <li class="step"><%= t('activity_level.steps.confirmation') %></li>
    </ul>
    <h1 class="text-2xl font-bold text-gray-800 text-center font-zenmaru mb-6"><%= t('activity_level.title') %></h1>
    <%= form_with url: save_activity_level_users_path, local: true, data: { turbo: false } do |f| %>
      <div class="bg-white rounded-lg p-6 shadow-md relative z-10">
        <div>
          <%= f.label :activity_level, t('activity_level.label'), class: "text-gray-700 text-lg font-zenmaru" %>
          <%= f.select :activity_level, [['低い', 'low'], ['適度', 'moderate'], ['高い', 'high']].map { |label, value| [t("activity_level.options.#{value}"), value] }, {}, {class: "w-full rounded-md font-zenmaru border-gray-300 text-lg"} %>
        </div>
        <div class="mt-8 text-center">
          <%= f.submit t('activity_level.next_button'), class: "btn btn-primary font-zenmaru w-full bg-cyan-300" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/allergies.html.erb
<div class="bg-teal-100 min-h-screen">
  <div class="absolute top-16 left-0 right-0 w-full animate-float1">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 640">
      <path fill="#5eead4" fill-opacity="1" d="M0,192L48,197.3C96,203,192,213,288,224C384,235,480,245,576,218.7C672,192,768,128,864,122.7C960,117,1056,171,1152,192C1248,213,1344,203,1392,197.3L1440,192L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
    </svg>
  </div>
  <div class="absolute top-18 left-0 right-0 w-full animate-float2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#5eead4" fill-opacity="0.5" d="M0,256L34.3,245.3C68.6,235,137,213,206,197.3C274.3,181,343,171,411,170.7C480,171,549,181,617,197.3C685.7,213,754,235,823,229.3C891.4,224,960,192,1029,181.3C1097.1,171,1166,181,1234,170.7C1302.9,160,1371,128,1406,112L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path>
    </svg>
  </div>
  <div class="max-w-lg mx-auto p-6 relative z-10">
    <ul class="steps steps-primary font-zenmaru">
      <li class="step step-primary"><%= t('allergies.steps.goal') %></li>
      <li class="step step-primary"><%= t('allergies.steps.profile') %></li>
      <li class="step step-primary"><%= t('allergies.steps.weight') %></li>
      <li class="step step-primary"><%= t('allergies.steps.activity') %></li>
      <li class="step step-primary"><%= t('allergies.steps.allergies') %></li>
      <li class="step"><%= t('allergies.steps.confirmation') %></li>
    </ul>
    <h1 class="text-2xl font-bold text-gray-800 text-center font-zenmaru mb-6"><%= t('allergies.title') %></h1>
    <%= form_with model: @user, url: save_allergies_users_path, local: true, data: { turbo: false } do |f| %>
      <div class="bg-white rounded-lg p-6 shadow-md relative z-10">
        <div>
          <%= f.label :allergy_item_ids, t('allergies.label'), class: "text-gray-700 font-zenmaru text-lg" %>
        </div>
        <div class="space-y-2 mt-2">
          <%= f.collection_check_boxes :allergy_item_ids, AllergyItem.all, :id, :name do |b| %>
            <label class="flex items-center">
              <%= b.check_box(class: "h-5 w-5 text-indigo-600 rounded focus:ring-indigo-500") %>
              <span class="ml-2 text-gray-700 font-zenmaru"><%= b.text %></span>
            </label>
          <% end %>
        </div>
        <div class="text-center mt-8">
          <%= f.submit t('allergies.confirm_button'), class: "btn btn-primary font-zenmaru bg-cyan-300 w-full" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/body_info.html.erb
<div class="bg-teal-100 min-h-screen">
  <div class="absolute top-16 left-0 right-0 w-full animate-float1">
    <svg class="svg-background" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 640">
      <path fill="#5eead4" fill-opacity="1" d="M0,192L48,197.3C96,203,192,213,288,224C384,235,480,245,576,218.7C672,192,768,128,864,122.7C960,117,1056,171,1152,192C1248,213,1344,203,1392,197.3L1440,192L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
    </svg>
  </div>
  <div class="absolute top-18 left-0 right-0 w-full animate-float2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#5eead4" fill-opacity="0.5" d="M0,256L34.3,245.3C68.6,235,137,213,206,197.3C274.3,181,343,171,411,170.7C480,171,549,181,617,197.3C685.7,213,754,235,823,229.3C891.4,224,960,192,1029,181.3C1097.1,171,1166,181,1234,170.7C1302.9,160,1371,128,1406,112L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path>
    </svg>
  </div>
  <div class="max-w-lg mx-auto px-6 py-12 relative z-10 md:max-w-lg">
    <ul class="steps">
      <li class="step step-primary secondary font-zenmaru"><%= t('body_info.steps.goal') %></li>
      <li class="step white font-zenmaru"><%= t('body_info.steps.profile') %></li>
      <li class="step font-zenmaru"><%= t('body_info.steps.weight') %></li>
      <li class="step font-zenmaru"><%= t('body_info.steps.activity') %></li>
      <li class="step font-zenmaru"><%= t('body_info.steps.allergies') %></li>
      <li class="step font-zenmaru"><%= t('body_info.steps.confirmation') %></li>
    </ul>
    <h1 class="text-2xl font-bold text-gray-800 text-center font-zenmaru mb-8"><%= t('body_info.title') %></h1>
    <%= form_with url: save_goal_users_path, local: true, data: { turbo: false } do |f| %>
      <div class="bg-white rounded-lg p-6 shadow-md relative z-10">
        <div class="space-y-4">
          <div class="flex items-center">
            <div class="flex items-center mr-5">
              <%= f.radio_button :goal, "standard", class: "h-5 w-5 text-indigo-600" %>
              <label class="ml-3 text-gray-700 text-lg font-zenmaru"><%= t('body_info.standard_body') %></label>
            </div>
            <div class="flex items-center">
              <%= f.radio_button :goal, "slim_muscle", class: "h-5 w-5 text-indigo-600" %>
              <label class="ml-3 text-gray-700 text-lg font-zenmaru"><%= t('body_info.slim_muscle') %></label>
            </div>
          </div>
        </div>
        <div class="mt-8 text-center">
          <%= f.submit t('body_info.next'), class: "btn btn-primary font-zenmaru w-full bg-cyan-300" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/confirmation.html.erb
<div class="bg-teal-100 min-h-screen p-4">
  <div class="absolute top-16 left-0 right-0 w-full animate-float1">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 640">
      <path fill="#5eead4" fill-opacity="1" d="M0,192L48,197.3C96,203,192,213,288,224C384,235,480,245,576,218.7C672,192,768,128,864,122.7C960,117,1056,171,1152,192C1248,213,1344,203,1392,197.3L1440,192L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
    </svg>
  </div>
  <div class="absolute top-18 left-0 right-0 w-full animate-float2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#5eead4" fill-opacity="0.5" d="M0,256L34.3,245.3C68.6,235,137,213,206,197.3C274.3,181,343,171,411,170.7C480,171,549,181,617,197.3C685.7,213,754,235,823,229.3C891.4,224,960,192,1029,181.3C1097.1,171,1166,181,1234,170.7C1302.9,160,1371,128,1406,112L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path>
    </svg>
  </div>
  <div class="max-w-md mx-auto relative z-10">
    <ul class="steps steps-primary py-4 font-zenmaru">
      <li class="step step-primary "><%= t('confirmation.steps.goal') %></li>
      <li class="step step-primary"><%= t('confirmation.steps.profile') %></li>
      <li class="step step-primary"><%= t('confirmation.steps.weight') %></li>
      <li class="step step-primary"><%= t('confirmation.steps.activity') %></li>
      <li class="step step-primary"><%= t('confirmation.steps.allergies') %></li>
      <li class="step step-primary"><%= t('confirmation.steps.confirmation') %></li>
    </ul>
    <div class="bg-white p-8 rounded-lg shadow-md">
      <div class="flex flex-col items-center font-zenmaru">
        <h2 class="text-lg font-medium mb-4"><%= t('confirmation.title') %></h2>
        <p class="font-medium"><%= t('confirmation.goal') %> <%= t("enums.user.goal.#{@goal}") %></p>
        <p class="font-medium"><%= t('confirmation.gender') %> <%= t("enums.user.gender.#{@gender_key}") %></p>
        <p class="font-medium"><%= t('confirmation.age') %> <%= @age %>歳</p>
        <p class="font-medium"><%= t('confirmation.height') %> <%= @height %>cm</p>
        <p class="font-medium"><%= t('confirmation.weight') %> <%= @weight %>kg</p>
        <p class="font-medium"><%= t('confirmation.target_weight') %> <%= @target_weight %>kg</p>
        <p class="font-medium"><%= t('confirmation.activity_level') %> <%= t("activity_level.options.#{@activity_level_key}") %></p>
        <p class="font-medium"><%= t('confirmation.allergies') %> <%= @allergy_names %></p>
        <div class="flex justify-center space-x-4">
          <%= link_to goal_users_path, class: "btn btn-primary flex items-center space-x-2" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
            </svg>
          <% end %>
          <%= link_to dashboard_home_path, class: "btn btn-success btn-outline flex items-center space-x-2" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/gender_age.html.erb
<div class="bg-teal-100 min-h-screen">
  <div class="absolute top-16 left-0 right-0 w-full animate-float1">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 640">
      <path fill="#5eead4" fill-opacity="1" d="M0,192L48,197.3C96,203,192,213,288,224C384,235,480,245,576,218.7C672,192,768,128,864,122.7C960,117,1056,171,1152,192C1248,213,1344,203,1392,197.3L1440,192L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path>
    </svg>
  </div>
  <div class="absolute top-18 left-0 right-0 w-full animate-float2">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#5eead4" fill-opacity="0.5" d="M0,256L34.3,245.3C68.6,235,137,213,206,197.3C274.3,181,343,171,411,170.7C480,171,549,181,617,197.3C685.7,213,754,235,823,229.3C891.4,224,960,192,1029,181.3C1097.1,171,1166,181,1234,170.7C1302.9,160,1371,128,1406,112L1440,96L1440,0L1405.7,0C1371.4,0,1303,0,1234,0C1165.7,0,1097,0,1029,0C960,0,891,0,823,0C754.3,0,686,0,617,0C548.6,0,480,0,411,0C342.9,0,274,0,206,0C137.1,0,69,0,34,0L0,0Z"></path>
    </svg>
  </div>
  <div class="max-w-lg mx-auto px-6 py-12 relative z-10">
    <ul class="steps steps-primary font-zenmaru">
      <li class="step step-primary font-zenmaru"><%= t('gender_age.steps.goal') %></li>
      <li class="step step-primary font-zenmaru"><%= t('gender_age.steps.profile') %></li>
      <li class="step font-zenmaru"><%= t('gender_age.steps.weight') %></li>
      <li class="step font-zenmaru"><%= t('gender_age.steps.activity') %></li>
      <li class="step font-zenmaru"><%= t('gender_age.steps.allergies') %></li>
      <li class="step font-zenmaru"><%= t('gender_age.steps.confirmation') %></li>
    </ul>
    <h1 class="text-2xl font-bold text-gray-800 text-center font-zenmaru mb-8"><%= t('gender_age.title') %></h1>
    <%= form_with url: save_gender_age_users_path, local: true, data: { turbo: false } do |f| %>
      <div class="bg-white rounded-lg p-6 shadow-lg relative z-10">
        <div class="space-y-4">
          <div class="flex items-center">
            <div class="flex-1">
              <%= f.label :gender, t('gender_age.gender_label'), class: "text-gray-700 text-lg font-zenmaru" %>
              <%= f.select :gender, User.genders.keys.map { |k| [t("enums.user.gender.#{k}"), k] }, { prompt: t('gender_age.gender_prompt') }, class: "w-full rounded-md border-gray-400 text-lg font-zenmaru shadow-sm" %>
            </div>
            <div class="flex-1 ml-5">
              <%= f.label :age, t('gender_age.age_label'), class: "text-gray-700 text-lg font-zenmaru" %>
              <%= f.number_field :age, placeholder: t('gender_age.age_placeholder'), class: "w-full rounded-md border-gray-400 text-lg font-zenmaru shadow-sm" %>
            </div>
          </div>
        </div>
        <div class="text-center mt-8">
          <%= f.submit t('gender_age.next'), class: "btn btn-primary font-zenmaru w-full bg-cyan-300" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="flex items-center justify-center min-h-screen bg-gray-100">
  <div class="px-8 py-12 mx-4 mt-12 mb-20 text-left bg-white shadow-md rounded-lg md:w-1/3 lg:w-1/4">
    <h1 class="text-3xl font-semibold text-center text-gray-700"><%= t('users.new.title') %></h1>
    <%= form_with model: @user, local: true, data: { turbo: false } do |f| %>
      <div class="mt-6">
        <%= f.label :name, t('users.new.name_label'), class: "label" %>
        <%= f.text_field :name, class: "input input-bordered bg-gray-100 w-full" %>
      </div>
      <div class="mt-6">
        <%= f.label :email, t('users.new.email_label'), class: "label" %>
        <%= f.email_field :email, autofocus: true, class: "input input-bordered bg-gray-100 w-full" %>
      </div>
      <div class="mt-6">
        <%= f.label :password, t('users.new.password_label'), class: "label" %>
        <%= f.password_field :password, placeholder: "6文字以上", class: "input input-bordered bg-gray-100 w-full" %>
      </div>
      <div class="mt-6">
        <%= f.label :password_confirmation, t('users.new.password_confirmation_label'), class: "label" %>
        <%= f.password_field :password_confirmation, class: "input input-bordered bg-gray-100 w-full" %>
      </div>
      <div class="text-center mt-8">
        <%= f.submit t('users.new.register_button'), class: "px-6 py-3 text-lg text-white bg-cyan-400 rounded-lg hover:bg-cyan-500 focus:outline-none focus:bg-sky-700 w-full" %>
      </div>
    <% end %>
    <div class="mt-8 text-center text-gray-600">
      <%= link_to t('users.new.login_link'), login_path, class: "text-sky-600 hover:underline" %>
    </div>
  </div>
</div>