config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'pages#home'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/home', to: 'pages#dashboard', as: 'dashboard_home'
  get 'recipe_suggestions/index', as: 'recipe_suggestions'

  # 利用規約とプライバシーポリシー
  get 'terms', to: 'pages#terms', as: 'pages_terms'
  get 'privacy', to: 'pages#privacy', as: 'pages_privacy'
  # ユーザー情報関連のルーティング
  resources :users do
    collection do
      get 'goal'
      get 'gender_age'
      get 'height_weight_target_weight'
      get 'activity_level'
      get 'allergies'
      get 'confirmation', to: 'users#confirmation'
      post 'save_goal', to: 'users#save_goal'
      post 'save_gender_age', to: 'users#save_gender_age'
      post 'save_height_weight_target_weight', to: 'users#save_height_weight_target_weight'
      post 'save_activity_level', to: 'users#save_activity_level'
      post 'save_allergies', to: 'users#save_allergies'
    end
    member do
      delete :destroy
    end
  end

  # プロフィール
  resource :profile, only: %i[show edit update]

  # ダッシュボード
  resources :dashboard, only: [:index]

  # レシピ関連
  resources :recipes, only: [:index, :show] do
    collection do
      get 'search'  # => /recipes/search
      get 'search_results'  # => /recipes/search_results
      get 'recipes/:id', to: 'recipes#show', as: :recipe
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="main_image font-bold z-50 max-w-md">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_class(message_type) %> px-4 py-3 rounded relative z-50 max-w-md" role="alert">
    <span class="block sm:inline"><%= message %></span>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fixed bottom-0 left-0 right-0 flex justify-between items-center h-20 bg-teal-300 shadow z-50">
  <%= link_to dashboard_home_path, class: "btn bg-teal-300 ml-6 flex flex-col items-center mr-2" do %>
  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
  </svg>
  <span class="hidden sm:inline">Home</span>
  <% end %>
  <%= link_to dashboard_index_path, class: "btn bg-teal-300 flex flex-col items-center" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
    </svg>
    <span class="hidden sm:inline">Dashboard</span>
  <% end %>
  <%= link_to recipe_suggestions_path, class: "btn bg-teal-300 flex flex-col items-center" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
    </svg>
    <span class="hidden sm:inline">Recipes</span>
  <% end %>
  <%= link_to search_recipes_path, class: "btn bg-teal-300 mr-6 flex flex-col items-center" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
    </svg>
    <span class="hidden sm:inline">Search</span>
  <% end %>
</footer>

app/views/shared/_form_group.html.erb
<div>
  <%= form.label attribute, t(label_key), class: "text-gray-700 text-lg" %>
  <%= form.text_field attribute, placeholder: t(placeholder_key), class: "w-full rounded-md border-gray-300 text-lg shadow-sm" %>
</div>

app/views/shared/_header.html.erb
<header class=" bg-teal-300 relative z-10">
    <div class="flex justify-between items-center p-4 h-20">
        <% if request.path == root_path ||
            request.path == '/users/goal' ||
            request.path == '/users/gender_age' ||
            request.path == '/users/height_weight_target_weight' ||
            request.path == '/users/activity_level' ||
            request.path == '/users/allergies' ||
            request.path == '/users/confirmation' %>
          <div class="w-16 h-16 rounded-full overflow-hidden">
            <%= image_tag 'logo2.jpg', alt: 'Fat Recipe Logo', class: 'w-full h-auto' %>
          </div>
        <% else %>
          <a href="/home" class="w-16 h-16 rounded-full overflow-hidden">
            <%= image_tag 'logo2.jpg', alt: 'Fat Recipe Logo', class: 'w-full h-auto' %>
          </a>
        <% end %>
        <div class="flex items-center">
            <div class="mr-4">
                <% if controller_name == "pages" && action_name == "home" %>
                    <% unless logged_in? %>
                        <!-- ボタンを表示 -->
                        <%= link_to t('defaults.try_it'), goal_users_path, class: "btn text-white rounded-full bg-cyan-400 font-zenmaru" %>
                    <% end %>
                <% else %>
                    <!-- ボタンを非表示 -->
                    <%= content_tag :div, class: "hidden" do %>
                        <button>t('defaults.try_it')</button>
                    <% end %>
                <% end %>
            </div>
            <div class="ml-5 pr-10 pb-12 align-items-center">
                <button class="absolute right-0 ml-auto">
                    <% if logged_in? %>
                        <div class="dropdown dropdown-end z-60">
                          <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                              <div class="w-10 rounded-full">
                              <%= image_tag current_user.avatar_url%>
                              </div>
                          </label>
                        <ul tabindex="0" class="bg-white menu menu-compact dropdown-content mt-3 p-2 shadow rounded-box w-52 z-60">
                            <li><%= link_to t('defaults.my_page'), profile_path, class: "block px-4 py-2 hover:bg-gray-250" %></li>
                            <li><%= link_to t('defaults.home'), dashboard_home_path, class: "block px-4 py-2 hover:bg-gray-250" %></li>
                            <li><%= link_to t('defaults.logout'), logout_path, data: { turbo_method: :delete }, class: "block px-4 py-2 hover:bg-gray-250" %></li>
                            <li><%= link_to t('defaults.terms_of_service'), pages_terms_path, class: "block px-4 py-2 hover:bg-gray-250" %></li>
                            <li><%= link_to t('defaults.privacy_policy'), pages_privacy_path, class: "block px-4 py-2 hover:bg-gray-250" %></li>
                        </ul>
                    <% elsif controller_name == 'user_sessions' or 'users' && action_name == 'new' %>
                    <% else %>
                        <%= link_to t('defaults.login'), login_path, class: "btn text-white font-zenmaru rounded-full bg-cyan-400" %>
                    <% end %>
                </button>
            </div>
        </div>
    </div>
</header>

app/views/shared/_user_stat.html.erb
<div class="stat">
  <div class="flex items-center">
    <i class="fas fa-<%= icon %> mr-2"></i>
    <div class="stat-title text-lg"><%= t(title_key) %></div>
  </div>
  <div class="stat-value text-2xl"><%= value.to_i.floor %> <%= t(unit_key, value: '') %></div>
  <div class="stat-desc"></div>
</div>