config/routes.rb
Rails.application.routes.draw do
  get 'oauths/oauth'
  get 'oauths/callback'
  resources :password_resets, only: %i[new create edit update]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'pages#home'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  get '/home', to: 'pages#dashboard', as: 'dashboard_home'
  get 'recipe_suggestions/index', as: 'recipe_suggestions'

  # 利用規約とプライバシーポリシー
  get 'terms', to: 'pages#terms', as: 'pages_terms'
  get 'privacy', to: 'pages#privacy', as: 'pages_privacy'
  # ユーザー情報関連のルーティング
  resources :users do
    collection do
      get 'goal'
      get 'gender_age'
      get 'height_weight_target_weight'
      get 'activity_level'
      get 'allergies'
      get 'confirmation', to: 'users#confirmation'
      post 'save_goal', to: 'users#save_goal'
      post 'save_gender_age', to: 'users#save_gender_age'
      post 'save_height_weight_target_weight', to: 'users#save_height_weight_target_weight'
      post 'save_activity_level', to: 'users#save_activity_level'
      post 'save_allergies', to: 'users#save_allergies'
    end
    member do
      delete :destroy
    end
  end

  # プロフィール
  resource :profile, only: %i[show edit update]

  # ダッシュボード
  resources :dashboard, only: [:index]

  # レシピ関連
  resources :recipes, only: [:index, :show] do
    collection do
      get 'search'  # => /recipes/search
      get 'search_results'  # => /recipes/search_results
      get 'recipes/:id', to: 'recipes#show', as: :recipe
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])  # 存在するか認証しユーザーオブジェクトを返す

    if @user && @user.deleted_at.nil?
      user = User.find(session[:user_id])
      session[:goal] = user.goal
      session[:gender] = user.gender
      session[:age] = user.age
      session[:height] = user.height
      session[:weight] = user.weight
      session[:target_weight] = user.target_weight
      session[:activity_level] = user.activity_level
      session[:allergy_item_ids] = user.allergy_item_ids
      session[:bmr] = user.bmr
      session[:tdee] = user.tdee
      session[:target_calorie] = user.target_calorie
      redirect_back_or_to dashboard_home_path, notice: t('.success')
    else
      reset_session
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    reset_session
    redirect_to root_path, notice: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<div class="flex items-center justify-center min-h-screen bg-gray-200">
  <div class="px-8 py-12 mx-4 text-left bg-white shadow-md rounded-lg md:w-1/3 lg:w-1/4">
    <h1 class="text-3xl font-semibold text-center text-gray-700"><%= t('user_sessions.new.title') %></h1>
    <%= form_with url: login_path, local: true, data: { turbo: false } do |f| %>
      <div class="mt-6">
        <%= f.label :email, t('user_sessions.new.email_label'), class: "block text-lg font-medium text-gray-600" %>
        <%= f.email_field :email, autofocus: true, class: "block w-full px-4 py-3 mt-2 bg-gray-100 border rounded-md focus:border-sky-500 focus:ring-sky-300 focus:outline-none focus:ring focus:ring-opacity-50" %>
      </div>
      <div class="mt-6">
        <%= f.label :password, t('user_sessions.new.password_label'), class: "block text-lg font-medium text-gray-600" %>
        <%= f.password_field :password,  placeholder: "6文字以上", class: "block w-full px-4 py-3 mt-2 bg-gray-100 border rounded-md focus:border-sky-500 focus:ring-sky-300 focus:outline-none focus:ring focus:ring-opacity-50" %>
      </div>
      <div class="flex items-center justify-center mt-8">
        <%= f.submit t('user_sessions.new.login_button'), class: "px-6 py-3 text-lg text-white bg-cyan-400 rounded-lg hover:bg-cyan-500 focus:outline-none focus:bg-sky-700 w-full" %>
      </div>
    <% end %>
    <div class="mt-8 text-center text-gray-600">
      <%= link_to t('user_sessions.new.register_link'), new_user_path, class: "text-sky-600 hover:underline" %>
      <%= link_to t('user_sessions.new.password_forget'), new_password_reset_path, class: "ml-4 text-sky-600 hover:underline" %>
      <p class="mt-4">
        <%= link_to t('user_sessions.new.forget'), goal_users_path, class: "text-sky-600 hover:underline" %>
      </p>
    </div>
  </div>
</div>